### ISSUE TITLE
Need more information on Token

### ISSUE THREAD

**Issue by VladimirCores** [swedesjs/vkdart#1]
Could you please describe in details how to obtain a token?

**Comment by swedesjs** [comment]
токен от группы или от страницы пользователя ВК?

**Comment by VladimirCores** [comment]
И от группы и от станицы пользователя.

**Comment by swedesjs** [comment]
страница вк - ![image](https://github.com/swedesjs/vkdart/assets/82697402/56c87936-b154-428e-b43c-3162852ebe2d)
сообщество - https://vk.com/@vksoftred-kak-poluchit-token-soobschestva-vkontakte

**Comment by VladimirCores** [comment]
Ок, думал что можно как то через API вашей библиотеки, но это тоже полезно, спасибо!
